add hw
Alexandr1899/nodejs-homework pull request #3
Opened 2023-01-22 16:35 UTC by Alexandr1899

2023-01-22 17:26 UTC, KhYulian requested changes
Потрібні правки

2023-01-22 17:26 UTC, KhYulian commented on middlewares/validation/loginValidation.js
> +});
Винесіть const schema в окремй файл

2023-01-22 17:26 UTC, KhYulian commented on middlewares/validation/registrationValidation.js
> +});
теж винесіть

2023-01-22 17:26 UTC, KhYulian commented on models/users.js
> +  return user;
Переконайтесь, ще не повретаєте password у респонсі. Можна перед return user написати user.password = null або вирішити цю проблему іншим чином

2023-01-22 18:58 UTC, Alexandr1899 commented on models/users.js
> +  return user;
зроблено

2023-01-22 18:58 UTC, Alexandr1899 commented on middlewares/validation/registrationValidation.js
> +});
зроблено

2023-01-22 18:58 UTC, Alexandr1899 commented on middlewares/validation/loginValidation.js
> +});
зроблено

2023-01-23 07:41 UTC, merged

2023-01-23 07:42 UTC, KhYulian reviewed
Чудова робота :)